const THEMES={
  rose:{name:'Rose milk',bg:'#fbf5f0',surface:'#fffaf6',surface2:'#f5ebe5',text:'#3e2730',muted:'#836b73',accent:'#d79ba1',accent2:'#7d3f46',soft:'#f1d9dc',line:'#eadad4'},
  sage:{name:'Sage',bg:'#f5f7f0',surface:'#fbfcf8',surface2:'#e9efe2',text:'#28362c',muted:'#718077',accent:'#9bb89f',accent2:'#4e7058',soft:'#dce9dd',line:'#dce5d8'},
  lavender:{name:'Lavender',bg:'#f7f3fb',surface:'#fcfaff',surface2:'#ede6f5',text:'#342c43',muted:'#776b85',accent:'#b7a2d5',accent2:'#675380',soft:'#e7def2',line:'#e4dbed'},
  peach:{name:'Peach',bg:'#fff5ef',surface:'#fffaf6',surface2:'#f8e6db',text:'#4b3028',muted:'#896f66',accent:'#e8ad90',accent2:'#985c4e',soft:'#f6ddd0',line:'#f1ded4'},
  butter:{name:'Butter',bg:'#fff9e9',surface:'#fffdf5',surface2:'#f7edca',text:'#403725',muted:'#83775d',accent:'#e7cb78',accent2:'#8b7130',soft:'#f6e9b8',line:'#eee2bd'},
  mint:{name:'Mint',bg:'#f0faf7',surface:'#f8fffc',surface2:'#def2eb',text:'#263b35',muted:'#69837b',accent:'#8bc8b6',accent2:'#407566',soft:'#d2eee5',line:'#d6ebe4'},
  lilac:{name:'Lilac',bg:'#fbf2fb',surface:'#fff9ff',surface2:'#f0dff0',text:'#432b43',muted:'#856d84',accent:'#d2a7cf',accent2:'#83547f',soft:'#ecd9eb',line:'#ebddeb'},
  sky:{name:'Sky',bg:'#f1f8fc',surface:'#f9fdff',surface2:'#dcecf5',text:'#293b47',muted:'#6d808a',accent:'#91bfd8',accent2:'#4d7489',soft:'#d8eaf4',line:'#d9e7ee'},
  cream:{name:'Cream',bg:'#faf7ee',surface:'#fffdf8',surface2:'#eee7d8',text:'#3f382c',muted:'#7f7767',accent:'#cbbd9f',accent2:'#77664d',soft:'#eee5d2',line:'#e6dfd2'},
  coral:{name:'Coral',bg:'#fff3f1',surface:'#fffaf9',surface2:'#f7ded9',text:'#4b2b2c',muted:'#896c6b',accent:'#e9a09a',accent2:'#9c514e',soft:'#f5d6d1',line:'#f0ddd9'},
  pistachio:{name:'Pistachio',bg:'#f7f9ef',surface:'#fcfdf8',surface2:'#e9eed2',text:'#35402d',muted:'#78806c',accent:'#b8ca83',accent2:'#65743f',soft:'#e0e8c5',line:'#e1e7d3'},
  mocha:{name:'Mocha',bg:'#f8f3f0',surface:'#fdfaf8',surface2:'#eee2dc',text:'#3f312d',muted:'#7f6f69',accent:'#b99b8f',accent2:'#6f5148',soft:'#e7d6cf',line:'#e5d9d3'}
};

const DARK_THEMES={
  rose:{bg:'#241b1e',surface:'#302326',surface2:'#3a292d',text:'#fff1f2',muted:'#d7b9bd',accent:'#d99ba4',accent2:'#f0b6bd',soft:'#51363c',line:'#63434a'},
  sage:{bg:'#18211b',surface:'#202c24',surface2:'#29372d',text:'#eef8f0',muted:'#b8cdbd',accent:'#9fc5a6',accent2:'#b9d9bf',soft:'#344a39',line:'#46604c'},
  lavender:{bg:'#201b29',surface:'#2a2336',surface2:'#352c44',text:'#f6f0ff',muted:'#c9bddd',accent:'#bca8dc',accent2:'#d2c2ee',soft:'#443858',line:'#594a70'},
  peach:{bg:'#261d19',surface:'#32251f',surface2:'#3e2d26',text:'#fff1e9',muted:'#d9bbae',accent:'#e7aa8c',accent2:'#f0bea7',soft:'#51392f',line:'#68483b'},
  butter:{bg:'#242116',surface:'#302b1b',surface2:'#3b3420',text:'#fff9df',muted:'#d6c99b',accent:'#dfc66f',accent2:'#f0da8e',soft:'#4b4227',line:'#605633'},
  mint:{bg:'#16231f',surface:'#1e2f29',surface2:'#263b34',text:'#ecfff8',muted:'#b2d5c9',accent:'#8bc8b6',accent2:'#b0dfd1',soft:'#304d43',line:'#3d6255'},
  lilac:{bg:'#251a25',surface:'#312231',surface2:'#3d2b3d',text:'#fff0ff',muted:'#d4b9d3',accent:'#d2a7cf',accent2:'#e4c1e1',soft:'#503950',line:'#674b66'},
  sky:{bg:'#17222a',surface:'#1e2d36',surface2:'#263944',text:'#effaff',muted:'#b7cfdb',accent:'#91bfd8',accent2:'#b9d8e8',soft:'#304a58',line:'#3e5d6e'},
  cream:{bg:'#211e18',surface:'#2b271f',surface2:'#373126',text:'#fffaf0',muted:'#cdc3ae',accent:'#cbbd9f',accent2:'#ded1b6',soft:'#484032',line:'#5d5341'},
  coral:{bg:'#271b1b',surface:'#332323',surface2:'#402c2b',text:'#fff0ee',muted:'#ddb9b5',accent:'#e9a09a',accent2:'#f2bbb6',soft:'#553937',line:'#6d4946'},
  pistachio:{bg:'#202319',surface:'#292e20',surface2:'#343a27',text:'#f7fbe9',muted:'#c8d0aa',accent:'#b8ca83',accent2:'#d0de9f',soft:'#444c31',line:'#58623f'},
  mocha:{bg:'#241d1a',surface:'#302622',surface2:'#3b2f2a',text:'#fff4ef',muted:'#d1bbb2',accent:'#b99b8f',accent2:'#d3b8ad',soft:'#4c3b35',line:'#625048'}
};
const SYMPTOMS=['kramp','şişkinlik','akne','baş ağrısı','göğüs hassasiyeti','yorgunluk','tatlı isteği','saç dökülmesi','ruh hali','kasık ağrısı','libido artışı','uykusuzluk'];
const LS='not28-data-v1';
const fmt=d=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const iso=d=>{const z=new Date(d);z.setMinutes(z.getMinutes()-z.getTimezoneOffset());return z.toISOString().slice(0,10)};
const add=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)};
const diff=(a,b)=>Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000);
const today=()=>iso(new Date());
let data=load(); let currentId=localStorage.getItem('not28-current')||null; let view='home'; let calOffset=0;
function load(){let d;try{d=JSON.parse(localStorage.getItem(LS))}catch{};if(!d||!d.profiles){d={profiles:[
 {id:'nisu',name:'Nisu',mode:'pcos',theme:'rose',dark:false,created:Date.now(),periods:[],symptoms:[],ovulation:[],notes:[],meds:[]},
 {id:'eda',name:'Eda',mode:'irregular',theme:'sage',dark:false,created:Date.now(),periods:[],symptoms:[],ovulation:[],notes:[],meds:[]},
 {id:'esra',name:'Esra',mode:'irregular',theme:'lavender',dark:false,created:Date.now(),periods:[],symptoms:[],ovulation:[],notes:[],meds:[]}
]};save(d)}return d}
function save(d=data){localStorage.setItem(LS,JSON.stringify(d))}
function p(){return data.profiles.find(x=>x.id===currentId)}
function mixHex(a,b,ratio){const pa=a.replace('#',''),pb=b.replace('#','');const ar=parseInt(pa.slice(0,2),16),ag=parseInt(pa.slice(2,4),16),ab=parseInt(pa.slice(4,6),16),br=parseInt(pb.slice(0,2),16),bg=parseInt(pb.slice(2,4),16),bb=parseInt(pb.slice(4,6),16);const m=(x,y)=>Math.round(x*(1-ratio)+y*ratio).toString(16).padStart(2,'0');return '#'+m(ar,br)+m(ag,bg)+m(ab,bb)}
function theme(){const pr=p();const light=THEMES[pr?.theme||'rose'];const t=pr?.dark?DARK_THEMES[pr?.theme||'rose']:light;const v={bg:t.bg,surface:t.surface,'surface-2':t.surface2,text:t.text,muted:t.muted,accent:t.accent,'accent-2':t.accent2,'accent-soft':t.soft,line:t.line};for(const [k,val] of Object.entries(v))document.documentElement.style.setProperty('--'+k,val);document.body.classList.toggle('dark',!!pr?.dark);document.querySelector('meta[name="theme-color"]').setAttribute('content',v.bg)}
function cycles(pr=p()){const starts=[...pr.periods].map(x=>x.start).sort();return starts.slice(1).map((s,i)=>diff(starts[i],s)).filter(x=>x>10&&x<180)}
function lastPeriod(pr=p()){return [...pr.periods].sort((a,b)=>b.start.localeCompare(a.start))[0]||null}
function cycleStats(pr=p()){const c=cycles(pr);if(!c.length)return{arr:[],avg:null,min:null,max:null,spread:null};const avg=Math.round(c.reduce((a,b)=>a+b,0)/c.length);return{arr:c,avg,min:Math.min(...c),max:Math.max(...c),spread:Math.max(...c)-Math.min(...c)}}
function prediction(pr=p()){const lp=lastPeriod(pr);if(!lp)return null;const s=cycleStats(pr);let low,high;if(s.arr.length>=2){low=Math.max(20,s.min);high=Math.min(120,s.max)}else if(pr.mode==='regular'){low=26;high=32}else if(pr.mode==='pcos'){low=30;high=60}else{low=28;high=45}return{periodStart:add(lp.start,low),periodEnd:add(lp.start,high),cycleDay:diff(lp.start,today())+1,low,high}}
function ovPred(pr=p()){const pred=prediction(pr);if(!pred)return null;const lp=lastPeriod(pr);const s=cycleStats(pr);let center=s.avg?Math.max(10,s.avg-14):pr.mode==='pcos'?28:14;let span=pr.mode==='pcos'?6:3;return{start:add(lp.start,Math.max(7,center-span)),end:add(lp.start,center+span),center:add(lp.start,center)} }
function render(){theme();document.getElementById('app').innerHTML=currentId&&p()?shell():gate();bind()}
function gate(){return `<main class="profile-gate"><section class="gate-card"><img class="gate-logo" src="assets/not28-logo-v4.png" alt="Not 28"><h1>kim kullanıyor?</h1><p>mail yok, şifre yok. profilini seç ve devam et.</p><div class="people">${data.profiles.map(x=>`<button class="person" data-person="${x.id}"><span class="avatar">${x.name[0].toUpperCase()}</span>${x.name}</button>`).join('')}</div><button class="soft-btn full" id="newPerson">＋ kişi oluştur</button><p style="font-size:12px;margin-top:14px">veriler bu cihazda, profillere ayrı ayrı kaydedilir.</p></section></main>`}
function shell(){return `<div class="app-shell"><header class="topbar"><div class="brand"><img src="assets/not28-logo-v4.png" alt="Not 28"><b>not 28</b></div><button class="profile-chip" id="switchProfile">${p().name}⌄</button></header><main class="page">${view==='home'?home():view==='calendar'?calendar():view==='analysis'?analysis():view==='profile'?profile():home()}</main><nav class="nav"><button data-view="home" class="${view==='home'?'active':''}"><span class="nav-ico">⌂</span>bugün</button><button data-view="calendar" class="${view==='calendar'?'active':''}"><span class="nav-ico">▦</span>takvim</button><button id="addMain"><span class="nav-ico">＋</span>kayıt</button><button data-view="analysis" class="${view==='analysis'?'active':''}"><span class="nav-ico">⌁</span>analiz</button><button data-view="profile" class="${view==='profile'?'active':''}"><span class="nav-ico">◉</span>profil</button></nav></div>`}
function home(){const pr=p(), lp=lastPeriod(pr), pred=prediction(pr), ov=ovPred(pr), st=cycleStats(pr);let warn='';if(lp&&diff(lp.start,today())>=90)warn=`<div class="warning" style="margin-top:12px"><b>90+ gündür kanama kaydı yok.</b><br><small>PCOS'ta uzun aralıklar görülebilir; bu durumda bir sağlık profesyoneliyle görüşmek iyi olur.</small></div>`;return `<section class="hero"><div class="eyebrow">${pr.mode==='pcos'?'pcos modu':'kişisel döngü'}</div><h1>${pred?`döngünün ${Math.max(1,pred.cycleDay)}. günü`:'ilk kaydını ekle'}</h1><p>${lp?`son regl başlangıcı ${fmt(lp.start)}.`:'Tahminler için en az bir regl başlangıcı kaydet.'}</p><div class="hero-grid"><div class="metric"><strong>${st.avg??'—'}</strong><span>ortalama döngü</span></div><div class="metric"><strong>${st.min&&st.max?`${st.min}–${st.max}`:'—'}</strong><span>kişisel aralık</span></div><div class="metric"><strong>${pr.periods.length}</strong><span>kayıtlı regl</span></div></div>${warn}</section><div class="section-title"><h2>şu an</h2><small>tahmin, kesinlik değil</small></div><div class="grid-2"><div class="card"><div class="eyebrow">sonraki regl</div><h3>${pred?`${fmt(pred.periodStart)} – ${fmt(pred.periodEnd)}`:'henüz yok'}</h3><p style="color:var(--muted);margin-bottom:0">${pr.mode==='pcos'?'PCOS nedeniyle tek gün yerine olası pencere gösteriliyor.':'Geçmiş kayıtlarına göre olası pencere.'}</p></div><div class="card"><div class="eyebrow">ovulasyon</div><h3>${ov?`${fmt(ov.start)} – ${fmt(ov.end)}`:'henüz yok'}</h3><p style="color:var(--muted);margin-bottom:0">${pr.mode==='pcos'?'Düzensiz ovulasyonda tahmin daha belirsiz olabilir. Not 28 bunu regl geçmişinden otomatik takip eder.':'Olası verimli dönem.'}</p></div></div><div class="section-title"><h2>hızlı kayıt</h2><small>2 dokunuş</small></div><div class="quick"><button data-add="period"><span class="ico">◉</span>regl</button><button data-add="symptom"><span class="ico">✦</span>belirti</button></div><div class="section-title"><h2>son kayıtlar</h2></div><div class="card">${recent()}</div>`}
function recent(){const pr=p();const rows=[...pr.periods.map(x=>({d:x.start,t:'regl',s:x.end?`${fmt(x.start)} → ${fmt(x.end)}`:fmt(x.start)})),...pr.symptoms.map(x=>({d:x.date,t:'belirti',s:x.items.join(', ')})),...pr.ovulation.map(x=>({d:x.date,t:'ovulasyon',s:[x.lh&&`LH ${x.lh}`,x.discharge&&x.discharge,x.temp&&`${x.temp}°C`].filter(Boolean).join(' · ')||'ovulasyon kaydı'})),...pr.notes.map(x=>({d:x.date,t:'not',s:x.text}))].sort((a,b)=>b.d.localeCompare(a.d)).slice(0,6);return rows.length?`<div class="list">${rows.map(r=>`<div class="list-row"><div><b>${r.t}</b><small>${r.s}</small></div><span class="badge">${fmt(r.d)}</span></div>`).join('')}</div>`:`<div class="empty">henüz kayıt yok.</div>`}
function calendar(){const now=new Date();const base=new Date(now.getFullYear(),now.getMonth()+calOffset,1);const y=base.getFullYear(),m=base.getMonth();const first=(new Date(y,m,1).getDay()+6)%7;const days=new Date(y,m+1,0).getDate();const prevDays=new Date(y,m,0).getDate();let cells=[];for(let i=0;i<42;i++){let num,yy=y,mm=m,out=false;if(i<first){num=prevDays-first+i+1;mm=m-1;out=true}else if(i>=first+days){num=i-first-days+1;mm=m+1;out=true}else num=i-first+1;const d=iso(new Date(yy,mm,num));cells.push(dayCell(d,num,out))}return `<div class="card"><div class="calendar-head"><button id="prevMonth">‹</button><h2>${new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(base)}</h2><button id="nextMonth">›</button></div><div class="weekdays">${['pt','sa','ça','pe','cu','ct','pa'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div><div class="legend"><span style="--c:#b85a66">regl</span><span style="--c:#e3abb3">tahmini regl</span><span style="--c:#7da994">verimli dönem</span><span style="--c:#8e7cc0">ovulasyon</span><span style="--c:#d5a665">belirti</span></div></div><div class="section-title"><h2>takvim mantığı</h2></div><div class="card"><p style="margin:0;color:var(--muted)">Not 28, özellikle PCOS modunda tek bir “kesin ovulasyon günü” göstermez. Geçmiş döngülerinden olası aralık üretir; gerçek kayıtların her zaman daha değerlidir.</p></div>`}
function dayCell(d,num,out){const pr=p();let dots=[];if(pr.periods.some(x=>d>=x.start&&d<=(x.end||x.start)))dots.push('period');const pred=prediction(pr);if(pred&&d>=pred.periodStart&&d<=pred.periodEnd)dots.push('pred');const ov=ovPred(pr);if(ov&&d>=ov.start&&d<=ov.end)dots.push('fertile');if(ov&&d===ov.center)dots.push('ov');if(pr.symptoms.some(x=>x.date===d))dots.push('sym');return `<button class="day ${out?'out':''} ${d===today()?'today':''}" data-day="${d}"><span class="num">${num}</span><span class="dots">${[...new Set(dots)].map(x=>`<i class="dot ${x}"></i>`).join('')}</span></button>`}
function analysis(){const st=cycleStats(), pr=p();const arr=st.arr.slice(-8);const max=Math.max(60,...arr);const freq={};pr.symptoms.forEach(s=>s.items.forEach(x=>freq[x]=(freq[x]||0)+1));const top=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,5);return `<div class="section-title"><h2>döngü analizi</h2><small>son kayıtlar</small></div><div class="grid-2"><div class="card"><div class="eyebrow">ortalama</div><h2>${st.avg?st.avg+' gün':'—'}</h2><p style="color:var(--muted)">${st.arr.length?`${st.min}–${st.max} gün aralığında`:'en az 2 regl başlangıcı gerekli'}</p></div><div class="card"><div class="eyebrow">değişkenlik</div><h2>${st.spread!=null?st.spread+' gün':'—'}</h2><p style="color:var(--muted)">${st.spread==null?'henüz hesaplanmadı':st.spread>10?'döngüler belirgin değişken':'döngüler daha yakın aralıkta'}</p></div></div><div class="section-title"><h2>döngü uzunlukları</h2></div><div class="card">${arr.length?`<div class="bar-chart">${arr.map((v,i)=>`<div class="bar-wrap"><span class="bar-val">${v}</span><div class="bar" style="height:${Math.max(8,v/max*100)}%"></div><span class="bar-label">${i+1}</span></div>`).join('')}</div>`:`<div class="empty">grafik için daha fazla regl başlangıcı kaydet.</div>`}</div><div class="section-title"><h2>içgörüler</h2></div><div class="card"><div class="insight"><div>⌁</div><div><b>${pr.mode==='pcos'?'PCOS uyumlu tahmin açık':'kişisel tahmin açık'}</b><p>Tek bir güne kilitlenmek yerine aralık gösteriyoruz.</p></div></div>${top.length?`<div class="insight"><div>✦</div><div><b>en sık belirtiler</b><p>${top.map(([n,c])=>`${n} (${c})`).join(', ')}</p></div></div>`:''}<div class="insight"><div>◌</div><div><b>ovulasyon doğrulama</b><p>Ovulasyon aralığı regl geçmişinden otomatik hesaplanır; PCOS'ta bu yalnızca tahmindir.</p></div></div></div>`}
function profile(){const pr=p();return `<div class="section-title"><h2>${pr.name}</h2><small>profil ayarları</small></div><div class="card"><div class="field"><label>döngü tipi</label><select id="modeSelect"><option value="regular" ${pr.mode==='regular'?'selected':''}>genelde düzenli</option><option value="irregular" ${pr.mode==='irregular'?'selected':''}>düzensiz</option><option value="pcos" ${pr.mode==='pcos'?'selected':''}>PCOS nedeniyle düzensiz</option></select></div><div class="switch-row"><div><b>dark mode</b><small style="display:block;color:var(--muted)">seçtiğin pastelin gece hali</small></div><button class="switch ${pr.dark?'on':''}" id="darkToggle"><i></i></button></div></div><div class="section-title"><h2>12 pastel tema</h2></div><div class="card"><div class="theme-grid">${Object.entries(THEMES).map(([k,t])=>{const sw=pr.dark?DARK_THEMES[k]:t;return `<button class="theme-swatch ${pr.theme===k?'on':''}" data-theme="${k}" aria-label="${t.name}" title="${t.name}" style="background:linear-gradient(145deg,${sw.bg},${sw.accent})"></button>`}).join('')}</div></div><div class="section-title"><h2>veriler</h2></div><div class="card"><div class="list-row"><div><b>yedek dışa aktar</b><small>bu profilin kayıtlarını JSON olarak indir</small></div><button class="soft-btn" id="exportBtn">indir</button></div><div class="list-row"><div><b>profil değiştir</b><small>aynı cihazdaki başka kişiye geç</small></div><button class="soft-btn" id="switch2">değiştir</button></div></div><div class="section-title"><h2>gizlilik</h2></div><div class="card"><p style="margin:0;color:var(--muted)">Mail hesabı olmadığı için veriler bu tarayıcı/cihazda saklanır. Aynı cihazı kullanan biri profil seçerek kayıtlara erişebilir. İleride PIN kilidi ve bulut senkronizasyonu eklenebilir.</p></div>`}
function modal(type='period',date=today()){const forms={period:`<div class="field"><label>başlangıç</label><input id="pStart" type="date" value="${date}"></div><div class="field"><label>bitiş (opsiyonel)</label><input id="pEnd" type="date"></div><div class="field"><label>yoğunluk</label><select id="pFlow"><option>hafif</option><option selected>orta</option><option>yoğun</option></select></div>`,symptom:`<div class="field"><label>tarih</label><input id="sDate" type="date" value="${date}"></div><div class="field"><label>belirtiler</label><div class="chips">${SYMPTOMS.map(x=>`<button class="chip" data-sym="${x}">${x}</button>`).join('')}</div></div><div class="field"><label>not</label><textarea id="sNote" placeholder="bugün nasıldı?"></textarea></div>`,ovulation:`<div class="field"><label>tarih</label><input id="oDate" type="date" value="${date}"></div><div class="field"><label>LH testi</label><select id="oLH"><option value="">seçilmedi</option><option>negatif</option><option>pozitif</option><option>belirsiz</option></select></div><div class="field"><label>servikal akıntı</label><select id="oDis"><option value="">seçilmedi</option><option>kuru</option><option>kremsi</option><option>sulu</option><option>yumurta akı</option></select></div><div class="field"><label>bazal sıcaklık °C</label><input id="oTemp" inputmode="decimal" placeholder="36.6"></div>`,note:`<div class="field"><label>tarih</label><input id="nDate" type="date" value="${date}"></div><div class="field"><label>not</label><textarea id="nText" placeholder="stresliydim, seyahatteydim, ilaç başladım..."></textarea></div>`};document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modalWrap"><section class="modal"><div class="modal-head"><h3>kayıt ekle</h3><button class="icon-btn" id="closeModal">×</button></div><div class="tabs">${[['period','regl'],['symptom','belirti'],['note','not']].map(([k,n])=>`<button data-tab="${k}" class="${type===k?'on':''}">${n}</button>`).join('')}</div><div id="formArea">${forms[type]}</div><button class="soft-btn primary full" id="saveEntry" data-type="${type}">kaydet</button></section></div>`);bindModal(forms,type,date)}
function bindModal(forms,type,date){document.getElementById('closeModal').onclick=()=>document.getElementById('modalWrap').remove();document.getElementById('modalWrap').onclick=e=>{if(e.target.id==='modalWrap')e.currentTarget.remove()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{type=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));document.getElementById('formArea').innerHTML=forms[type];document.getElementById('saveEntry').dataset.type=type;bindSym()});bindSym();document.getElementById('saveEntry').onclick=saveEntry}
function bindSym(){document.querySelectorAll('[data-sym]').forEach(b=>b.onclick=e=>{e.preventDefault();b.classList.toggle('on')})}
function saveEntry(){const pr=p(),t=document.getElementById('saveEntry').dataset.type;if(t==='period'){const start=pStart.value,end=pEnd.value;if(!start)return toast('başlangıç tarihi gerekli');pr.periods.push({id:crypto.randomUUID(),start,end,flow:pFlow.value})}if(t==='symptom'){const items=[...document.querySelectorAll('[data-sym].on')].map(x=>x.dataset.sym);if(!items.length&&!sNote.value.trim())return toast('en az bir belirti ya da not ekle');pr.symptoms.push({id:crypto.randomUUID(),date:sDate.value,items,note:sNote.value.trim()})}if(t==='ovulation'){pr.ovulation.push({id:crypto.randomUUID(),date:oDate.value,lh:oLH.value,discharge:oDis.value,temp:oTemp.value})}if(t==='note'){if(!nText.value.trim())return toast('not boş olmasın');pr.notes.push({id:crypto.randomUUID(),date:nDate.value,text:nText.value.trim()})}save();document.getElementById('modalWrap').remove();toast('kaydedildi');render()}
function newPerson(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modalWrap"><section class="modal"><div class="modal-head"><h3>kişi oluştur</h3><button class="icon-btn" id="closeModal">×</button></div><div class="field"><label>adı</label><input id="newName" placeholder="ör. deniz" maxlength="20"></div><div class="field"><label>döngü tipi</label><select id="newMode"><option value="regular">genelde düzenli</option><option value="irregular" selected>düzensiz</option><option value="pcos">PCOS nedeniyle düzensiz</option></select></div><button class="soft-btn primary full" id="createPerson">oluştur</button></section></div>`);closeModal.onclick=()=>modalWrap.remove();createPerson.onclick=()=>{const name=newName.value.trim();if(!name)return toast('isim yaz');const id='p'+Date.now();data.profiles.push({id,name,mode:newMode.value,theme:'rose',dark:false,created:Date.now(),periods:[],symptoms:[],ovulation:[],notes:[],meds:[]});save();currentId=id;localStorage.setItem('not28-current',id);modalWrap.remove();render()}}
function bind(){document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{currentId=b.dataset.person;localStorage.setItem('not28-current',currentId);view='home';render()});document.getElementById('newPerson')?.addEventListener('click',newPerson);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.getElementById('addMain')?.addEventListener('click',()=>modal());document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>modal(b.dataset.add));document.getElementById('switchProfile')?.addEventListener('click',switchProfile);document.getElementById('switch2')?.addEventListener('click',switchProfile);document.getElementById('prevMonth')?.addEventListener('click',()=>{calOffset--;render()});document.getElementById('nextMonth')?.addEventListener('click',()=>{calOffset++;render()});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>modal('period',b.dataset.day));document.getElementById('modeSelect')?.addEventListener('change',e=>{p().mode=e.target.value;save();toast('döngü tipi güncellendi');render()});document.getElementById('darkToggle')?.addEventListener('click',()=>{p().dark=!p().dark;save();render()});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{p().theme=b.dataset.theme;save();render()});document.getElementById('exportBtn')?.addEventListener('click',exportProfile)}
function switchProfile(){localStorage.removeItem('not28-current');currentId=null;render()}
function exportProfile(){const blob=new Blob([JSON.stringify(p(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`not28-${p().name.toLowerCase()}-yedek.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker-v4.js').catch(()=>{}));
render();
